### ISSUE TITLE
Crash when accepting calendar invite from LS 

### ISSUE THREAD

**Issue by mletang** [douglas-srs/Safe-Alarm-3-iOS-10#1]
Beta 3 crashes every time I accept a calendar invite from lockscreen.
iPhone 7 10.1.1
Crash report emailed.

**Comment by douglas-srs** [comment]
Can you please send me a screenshot before you accept the invite?


----------------------------

Att,
*Douglas Soares*

**Comment by douglas-srs** [comment]
Please try now with version 3.0.3b
