### ISSUE TITLE
Fade in time

### ISSUE THREAD

**Issue by Grisu70** [douglas-srs/Safe-Alarm-3-iOS-10#10]
I used 3 minutes in fadein option to reach the maximum volume ..
Volume starts ti fadein and after 20 secs more or less the volume do not increase anymore

**Comment by douglas-srs** [comment]
Thanks for reporting, are you using a Stock Ringtone, a custom one or a music?

**Comment by douglas-srs** [comment]
Also, were you on Springboard or Lockscreen when that happened?

**Comment by Grisu70** [comment]
Music

Inviato da iPhone

**Comment by Grisu70** [comment]
Tried on lock screen

**Comment by douglas-srs** [comment]
Thanks, I will make some tests.

**Comment by Grisu70** [comment]
may be related to bug #9 ?
Fabrizio

**Comment by douglas-srs** [comment]
Probably. See issue 9 for details.

**Comment by douglas-srs** [comment]
Just released a new beta, try it please.

**Comment by Grisu70** [comment]
Hi, still the same

**Comment by douglas-srs** [comment]
that's weird, I will add some logs to tomorrow's update and then you try and send me the logs it will generate.

**Comment by douglas-srs** [comment]
I will release a new beta in a few hours, may you please remove the tweak and restart your phone before installing it again? Something might be cached on your phone because I tested this over and over and couldn't find the issue.

**Comment by Grisu70** [comment]
damn....
i lost my jb :(

Il 23/03/2017 18:06, douglas-srs ha scritto:

**Comment by douglas-srs** [comment]
Oh no :(


----------------------------

Att,
*Douglas Soares*

**Comment by Grisu70** [comment]
yes a nightmare :(

Il 23/03/2017 21:25, douglas-srs ha scritto:
> Oh no :(
>
>
> ----------------------------
>
> Att,
> *Douglas Soares*
>
