### ISSUE TITLE
Springboard crashes when interacting with any system default notification

### ISSUE THREAD

**Issue by mletang** [douglas-srs/Safe-Alarm-3-iOS-10#2]
I.e. Messages - quick reply 
Mail - mark as read, delete

**Comment by douglas-srs** [comment]
I already know what's causing the issue, I will have a fix for that
tomorrow too. thanks


----------------------------

Att,
*Douglas Soares*

**Comment by stryk3rr3al** [comment]
Crashes for me when pressing snooze/stop alarm as well.Pretty sure this is included in the above statement though

**Comment by douglas-srs** [comment]
Please try now with version 3.0.3b
