### ISSUE TITLE
Activator gestures 

### ISSUE THREAD

**Issue by stryk3rr3al** [douglas-srs/Safe-Alarm-3-iOS-10#5]
Activator gestures don't seem to do anything.Have tested several listeners to different action and still no functionality.

**Comment by douglas-srs** [comment]
Hello,

Snooze/Stop Actions will only work when an alarm is fired.
Turn On/Off all alarms should work whenever you are, to verify you can use
them while the Clock App is open and see if it changes anything.
The Light Mode Action needs to have the Clock App open as well to verify it
works.

Can you do these steps and confirm it's not working please?

Thank you.


----------------------------

Att,
*Douglas Soares*

**Comment by stryk3rr3al** [comment]
Opening the clock app seems to have no affect  on turning on/off all alarms.Trid a couple of different listiners again

**Comment by douglas-srs** [comment]
I am looking into this.

**Comment by douglas-srs** [comment]
Sorry for the delay but I couldn't find the issue with this yet, I asked more testers to test this, let's wait for their feedback.

**Comment by douglas-srs** [comment]
Until now no one reported issue with Activator, SA3 has already been submitted to The Big Boss repo, once it's out we will know for sure if there is a bug, thanks for helping!
