### ISSUE TITLE
Quick actions (delete, mark as read) not working 

### ISSUE THREAD

**Issue by mletang** [douglas-srs/Safe-Alarm-3-iOS-10#7]
From lockscreen and unlocked, when interacting with a notification (i.e. an email notification from the Mail app) marking as read or delete closes the notification but does not execute the action. 

Same issue when swiping a notification on the lockscreen to launch the app. The phone asks for fingerprint to unlock but just opens to springboard. 

All functions return when disabling safe alarm

**Comment by douglas-srs** [comment]
Hmmm Thank you for reporting, I will make some changes and release a new beta soon.

**Comment by douglas-srs** [comment]
Ok, I think I found the issue, next beta coming in the next few hours.

**Comment by mletang** [comment]
Great,thanks for the quick turnaround!

**Comment by douglas-srs** [comment]
Just released a new beta, try it please.
