### ISSUE TITLE
Garbled status bar

### ISSUE THREAD

**Issue by Grisu70** [douglas-srs/Safe-Alarm-3-iOS-10#8]
Scrolling the options of safe alarm 3 in settings make the status bar garbled. Is it possible to attach a screenshot?

**Comment by douglas-srs** [comment]
yes, you can attach files in here by dragging & dropping it

**Comment by Grisu70** [comment]
Inviato da iPhone

**Comment by Grisu70** [comment]
I was trying to add from iphone.
from my pc i have no problem pls find screenshot 
![garbled](https://cloud.githubusercontent.com/assets/21982285/23636380/70265184-02d5-11e7-800e-4303117c5526.PNG)

**Comment by douglas-srs** [comment]
I will check this out.

**Comment by douglas-srs** [comment]
Alright, I had the same issue and it disappeared after removing a couple of tweaks, can you please send me your package list? just go through Safe Alarm 3 Settings > About > email support and the file will be attached automaticaly.

**Comment by douglas-srs** [comment]
Actually it just happened to me again, I will have to make more tests, I still want your package files though.

**Comment by Grisu70** [comment]
Sending now

**Comment by douglas-srs** [comment]
I talked with some devs and it looks like it's an iOS 10 bug, it happens mostly in 10.2. what version are you in?

**Comment by Grisu70** [comment]
Hi,
i'm on 10.2.
Anyway It started happen with safe alarm installation, and disappear when safe alarm is uninstalled.

Fabrizio

**Comment by Grisu70** [comment]
I forgot .. sometime (when sa3 is installed) the status bar completely disappear.

Fabrizio

**Comment by douglas-srs** [comment]
I was without SA3 installed the whole day and the status bar issue kept happening to me, maybe something in SA3 is triggering it more frequently, I will keep looking anyway.
