### ISSUE TITLE
Default settings

### ISSUE THREAD

**Issue by Grisu70** [douglas-srs/Safe-Alarm-3-iOS-10#9]
Default settings are not always apllied when creating new alarms.

**Comment by douglas-srs** [comment]
Can you please provide some kind of instructions to reproduce the issue?

**Comment by Grisu70** [comment]
After a respring it seems working now. 
For example i choose 3 minutes fadein, and when creating alarm it was 10 sec.

**Comment by Grisu70** [comment]
Indefault settings for alarm i would add the snooze duration.
It seems there is no option to set a default value for it

**Comment by Grisu70** [comment]
Hi, I managed to repro also after respring.
it seems that settings are lost when you use the slider  for volume. 
i  recorded a video but it is 30 MB how can i send ?

Fabrizio

**Comment by Grisu70** [comment]
I shared on dropbox

https://www.dropbox.com/s/513jv9u608tylbm/IMG_2130.mp4?dl=0

Fabrizio

**Comment by douglas-srs** [comment]
Thank you, I will make some tests and let you know.

**Comment by douglas-srs** [comment]
I just fixed one bug related to Default Settings and will release a new beta in a few hours, please test after that. Thank you.

**Comment by douglas-srs** [comment]
Just released a new beta, try it please.

**Comment by Grisu70** [comment]
This seems solved
